#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    #to get the screen_name from input
    screen_name = sys.argv[1].strip('@')
    
    # get screen_name's tweets
    tweets = helpers.get_user_timeline(screen_name , 50)
    
    if tweets == None:
        sys.exit("User is private or doesn't exist")
        
        
    # analyze each tweet
    for each in tweets:
        score = analyzer.analyze(each)
        if score > 0.0:
            print(colored(" {} {}".format(score , each) , "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score , each) , "red"))
        else:
            print(colored(" {} {}".format(score , each) , "yellow"))

if __name__ == "__main__":
    main()